Repository jeremielenoir/oostaoo-coding-adventure, pull requests merged in 2022-09, with the labels that each got.

#490 Feature/#489/interview server client video chat rework
  interview/client/package.json
  interview/client/src/Pages/InterviewHomePage/InterviewHomePage.jsx
  interview/client/src/common/dico.js
  interview/client/src/components/ChatSection/ChatSection.jsx
  interview/client/src/components/Interview/Interview.jsx
  interview/client/src/components/Interview/interview.css
  interview/client/yarn.lock
  interview/server/index.js
Labels: enhancement, in progress, Ready for review

#492 Feature/#491/INTERVIEW CLIENT - PUT VIDEO CHAT LOGIC IN CONTEXT
  interview/client/src/App.jsx
  interview/client/src/Pages/InterviewHomePage/InterviewHomePage.jsx
  interview/client/src/common/StreamContext.js
  interview/client/src/components/Interview/Interview.jsx
  interview/client/src/components/Preview/Preview.jsx
Labels: enhancement, Ready for review

#493 Feature/#419/Lock_User_Microphone
  interview/client/src/Pages/InterviewHomePage/InterviewHomePage.jsx
  interview/client/src/common/StreamContext.js
  interview/client/src/components/CommandsBar/CommandsBar.jsx
  interview/client/src/components/Interview/Interview.jsx
Labels: bug

#497 FEATURE/#494/PARTNER_VIDEO_THUMBNAIL_FIX
  interview/client/src/common/StreamContext.js
  interview/client/src/components/CommandsBar/CommandsBar.jsx
  interview/client/src/components/CommandsBar/CommandsBar.test.js
  interview/client/src/components/CommandsBar/commandsBar.css
  interview/client/src/components/Interview/Interview.jsx
Labels: bug, enhancement, Ready for review

#498 FEATURE/#496/INTERVIEW CLIENT/SERVER - CREATE DISCONNECT LOGIC FOR STREAM AND ROOM
  interview/client/src/common/StreamContext.js
  interview/client/src/components/CommandsBar/CommandsBar.jsx
  interview/client/src/components/Interview/Interview.jsx
  interview/client/src/components/ModalLeaveInterview/ModalLeaveInterview.jsx
  interview/server/index.js
Labels: enhancement, Ready for review

#505 FIX/#504/UPDATE_ALL_TEST
  interview/client/package.json
  interview/client/src/App.test.js
  interview/client/src/Pages/InterviewHomePage/InterviewHomePage.test.js
  interview/client/src/Pages/LoggedOffPage/InterviewDeconnect.test.js
  interview/client/src/common/StreamContext.js
  interview/client/src/components/ChatSection/ChatSection.test.js
  interview/client/src/components/Interview/Interview.test.js
  interview/client/src/components/ModalLeaveInterview/ModalLeaveInterview.test.js
  interview/client/src/components/Preview/Preview.test.js
  interview/server/index.js
Labels: Ready for review

#507 FEAT/UPDATE README + CHANGED ONE LINE OF CODE
  interview/client/README.md
  interview/client/src/common/StreamContext.js
Labels: Ready for review

#509 Feature/#506/interview client readme update
  interview/server/index.js
Labels: bug, Ready for review
